config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :logins
  resources :inicios
  root to: 'inicios#index'

end

app/models/inicio.rb
class Inicio < ActiveRecord::Base
end

app/models/login.rb
class Login < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inicios_controller.rb
class IniciosController < ApplicationController
  before_action :set_inicio, only: [:show, :edit, :update, :destroy]

  # GET /inicios
  # GET /inicios.json
  def index
    @inicios = Inicio.all
  end

  # GET /inicios/1
  # GET /inicios/1.json
  def show
  end

  # GET /inicios/new
  def new
    @inicio = Inicio.new
  end

  # GET /inicios/1/edit
  def edit
  end

  # POST /inicios
  # POST /inicios.json
  def create
    @inicio = Inicio.new(inicio_params)

    respond_to do |format|
      if @inicio.save
        format.html { redirect_to @inicio, notice: 'Inicio was successfully created.' }
        format.json { render :show, status: :created, location: @inicio }
      else
        format.html { render :new }
        format.json { render json: @inicio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inicios/1
  # PATCH/PUT /inicios/1.json
  def update
    respond_to do |format|
      if @inicio.update(inicio_params)
        format.html { redirect_to @inicio, notice: 'Inicio was successfully updated.' }
        format.json { render :show, status: :ok, location: @inicio }
      else
        format.html { render :edit }
        format.json { render json: @inicio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inicios/1
  # DELETE /inicios/1.json
  def destroy
    @inicio.destroy
    respond_to do |format|
      format.html { redirect_to inicios_url, notice: 'Inicio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inicio
      @inicio = Inicio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inicio_params
      params.require(:inicio).permit(:usuario, :contrasena)
    end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  before_action :set_login, only: [:show, :edit, :update, :destroy]

  # GET /logins
  # GET /logins.json
  def index
    @logins = Login.all
  end

  # GET /logins/1
  # GET /logins/1.json
  def show
  end

  # GET /logins/new
  def new
    @login = Login.new
  end

  # GET /logins/1/edit
  def edit
  end

  # POST /logins
  # POST /logins.json
  def create
    @login = Login.new(login_params)

    respond_to do |format|
      if @login.save
        format.html { redirect_to @login, notice: 'Login was successfully created.' }
        format.json { render :show, status: :created, location: @login }
      else
        format.html { render :new }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logins/1
  # PATCH/PUT /logins/1.json
  def update
    respond_to do |format|
      if @login.update(login_params)
        format.html { redirect_to @login, notice: 'Login was successfully updated.' }
        format.json { render :show, status: :ok, location: @login }
      else
        format.html { render :edit }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logins/1
  # DELETE /logins/1.json
  def destroy
    @login.destroy
    respond_to do |format|
      format.html { redirect_to logins_url, notice: 'Login was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_login
      @login = Login.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def login_params
      params.require(:login).permit(:nusuario, :ncon)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inicios_helper.rb
module IniciosHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/views/inicios/_form.html.erb
<%= form_for(@inicio) do |f| %>
  <% if @inicio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inicio.errors.count, "error") %> prohibited this inicio from being saved:</h2>

      <ul>
      <% @inicio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :usuario %><br>
    <%= f.text_field :usuario %>
  </div>
  <div class="field">
    <%= f.label :contrasena %><br>
    <%= f.text_field :contrasena %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inicios/edit.html.erb
<h1>Editing Inicio</h1>

<%= render 'form' %>

<%= link_to 'Show', @inicio %> |
<%= link_to 'Back', inicios_path %>

app/views/inicios/index.html.erb
<div class="page-body">
<h1>What is translation Community Source?</h1>
<h3>This community provides the posibility to get assistant of the traduction of different 
types of archives with the objective of get a proffesional translation from the community users.

Are you interesting in start your own business or studies with your knowledge of languages? Start now!

You can give assistan to the community users for get valorations and a reputation on the site, so

the business interesting in translate archives, can the possibility to contact you and pay for the service

Start now! Join to the community and start a great trip of possibilities in the network!


</h3>

<%= image_tag('inicio1.png') %>

<h1>What is the purpose??</h1>
<h3>The purpose is help to the people that needs assistance in a determinate language.

Is a great opportunity for the business to get traductors rapid and timely manner and a opportunity

to the languages students for get a better domain of language.
</h3>
<%= image_tag('inicio2.jpg') %>

<td>
<form action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="H8CT3QUV9FMPJ">
<input type="image" src="https://www.sandbox.paypal.com/es_XC/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal, la forma más segura y rápida de pagar en línea.">
<img alt="" border="0" src="https://www.sandbox.paypal.com/es_XC/i/scr/pixel.gif" width="1" height="1">
</form>


</td>



</div>

app/views/inicios/new.html.erb
<h1>New Inicio</h1>

<%= render 'form' %>

<%= link_to 'Back', inicios_path %>

app/views/inicios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usuario:</strong>
  <%= @inicio.usuario %>
</p>

<p>
  <strong>Contrasena:</strong>
  <%= @inicio.contrasena %>
</p>

<%= link_to 'Edit', edit_inicio_path(@inicio) %> |
<%= link_to 'Back', inicios_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Proyecto</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Boton sw Inicio Comunity Source -->
      <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Translation Comunity Source</a>
    </div>

    <!-- Boton Inicio -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <% if user_signed_in?%>
      <li class="active"><a href="#"><%=link_to "Home",inicios_path %><span class="sr-only">(current)</span></a></li>
      <li class="active"><a href="#"><%=link_to "Edit Profile",edit_user_registration_path %><span class="sr-only">(current)</span></a></li>|
      <li class="active"><a href="#"><%=link_to "Log out",destroy_user_session_path, method: :delete %><span class="sr-only">(current)</span></a></li>
      <%else %>
        <li class="active"><a href="#"><%=link_to "Home",inicios_path %><span class="sr-only">(current)</span></a></li>
        <li class="active"><a href="#"><%=link_to "Sign Up",new_user_registration_path %><span class="sr-only">(current)</span></a></li>|
        <li class="active"><a href="#"><%=link_to "Login",new_user_session_path %><span class="sr-only">(current)</span></a></li>
     <%end%>
      </ul>
      
      <!-- Buscador de Textos --> 
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Text Name">
        </div>
        <button type="submit" class="btn btn-default">Search</button>
      </form>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->

</nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/logins/_form.html.erb
<%= form_for(@login) do |f| %>
  <% if @login.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@login.errors.count, "error") %> prohibited this login from being saved:</h2>

      <ul>
      <% @login.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nusuario %><br>
    <%= f.text_field :nusuario %>
  </div>
  <div class="field">
    <%= f.label :ncon %><br>
    <%= f.text_field :ncon %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/logins/edit.html.erb
<h1>Editing Login</h1>

<%= render 'form' %>

<%= link_to 'Show', @login %> |
<%= link_to 'Back', logins_path %>

app/views/logins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Logins</h1>

<table>
  <thead>
    <tr>
      <th>Nusuario</th>
      <th>Ncon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @logins.each do |login| %>
      <tr>
        <td><%= login.nusuario %></td>
        <td><%= login.ncon %></td>
        <td><%= link_to 'Show', login %></td>
        <td><%= link_to 'Edit', edit_login_path(login) %></td>
        <td><%= link_to 'Destroy', login, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Login', new_login_path %>

app/views/logins/new.html.erb
<h1>New Login</h1>

<%= render 'form' %>

<%= link_to 'Back', logins_path %>

app/views/logins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nusuario:</strong>
  <%= @login.nusuario %>
</p>

<p>
  <strong>Ncon:</strong>
  <%= @login.ncon %>
</p>

<%= link_to 'Edit', edit_login_path(@login) %> |
<%= link_to 'Back', logins_path %>